import Head from "next/head"
import Image from "next/image"
import { GetStaticProps } from "next"

import styles from "../styles/Home.module.scss"
import Footer from "../components/Footer"
import Hero from "../components/Hero"
import FeaturedCats from "../components/FeaturedCats"

import { BsArrowRight } from "react-icons/bs"
import axios from "axios"
import Link from "next/link"

export default function Home({ breeds }: any) {
  return (
    <div>
      <Head>
        <title>Cat Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["hero-container"]}>
        <Link href="/">
          <Image
            className={styles.logo}
            src="/CatwikiLogo.svg"
            width="120"
            height="44"
          />
        </Link>

        <Hero breeds={breeds} />
        <FeaturedCats cats={breeds.slice(0, 4)} />

        <div className={styles["info-container"]}>
          <div className={styles.info}>
            <div className={styles.divider}></div>
            <h2>
              Why should you <br /> have a cat?
            </h2>
            <p>
              Having a cat around you can actually trigger the <br /> release of
              calming chemicals in your body which
              <br /> lower your stress and anxiety leves
            </p>
            <div
              style={{
                display: "flex",
                cursor: "pointer",
              }}
            >
              <p className={styles["read-more"]}>Read more</p>

              <BsArrowRight className={styles["arrow-icon"]} />
            </div>
          </div>
          <div className={styles["info-images"]}>
            <div className={styles.col1}>
              <div>
                <Image src="/image2.webp" width={275} height={167} />
              </div>
              <div style={{ marginLeft: "80px", marginTop: "30px" }}>
                <Image src="/image1.webp" width={195} height={294} />
              </div>
            </div>
            <div className={styles.col2}>
              <Image src="/image3.webp" width={240} height={395} />
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.get("https://catwikiapi.herokuapp.com/cats")
  const breeds = res.data
  return {
    props: { breeds },
  }
}
